
export const MOVIE_FETCH_START = 'MOVIE_FETCH_START';
export const MOVIE_FETCH_RES = 'MOVIE_FETCH_RES';
export const MOVIE_FETCH_ERR = 'MOVIE_FETCH_ERR';


export const GENRE_FETCH_START = 'GENRE_FETCH_START';
export const GENRE_FETCH_RES = 'GENRE_FETCH_RES';
export const GENRE_FETCH_ERROR = 'GENRE_FETCH_ERROR';


export const NOW_PLAYING_FECTH = 'NOW_PLAYING_FECTH'
export const NOW_PLAYING_RES = 'NOW_PLAYING_RES'
export const NOW_PLAYING_ERR = 'NOW_PLAYING_ERR'